mdevctl/mdevctl

- Makefile
$(DESTDIR) already adds a trailing '/', so drop it. Cosmetic only.
> Makefile: drop extra '/'

- README
Calling `uuidgen` inline with create-mdev makes it hard to figure
out which device was created if mdevctl is invoked concurrently
multiple times. Better make the invocation of uuidgen explicit in
the example.
> README: avoid inline `uuidgen`

- mdevctl
man readlink recommends to use realpath for canonicalization; it
is also a bit shorter.
> use realpath for canonicalization

- mdevctl
This makes it easier to figure out the index of an attribute
one might want to modify.
Before:
783e6dbb-ea0e-411f-94e2-717eaad438bf matrix vfio_ap-passthrough manual
Attrs: {"assign_adapter":["5","6"]} {"assign_domain":["4","0xab"]}
After:
783e6dbb-ea0e-411f-94e2-717eaad438bf matrix vfio_ap-passthrough manual
Attrs:
@{0}: {"assign_adapter":["5","6"]}
@{1}: {"assign_domain":["4","0xab"]}
> print index when listing attributes

- README
- mdevctl
Instead of automatically parsing a list of values for an attribute
into an array and then writing each value to the attribute
individually, just write the value given to the attribute as-is.
While this makes specifying lists of values a bit more tedious
(although it is probably better to write a config file directly
for complex configurations anyway), it gives us some benefits:
- no weird escaping if you explicitly want to specify a comma-
separated list of values for an attribute
- you can delete one value for an attribute explicitly (by index),
no need to delete the whole range and re-add
- slightly simpler parsing code
Note: existing configs with attributes are not converted.
> simplify attribute handling

- README
- mdevctl.8
Attributes are now only printed with -v|--verbose.
> fix attribute output examples

- Makefile
- mdevctl.8
lsmdev was installed as symlinked alternative name, but up until this patch
is neither mentioned in the man pages NAME section of mdevctl.8 nor has a
symlinked man page file that would allof to find `man lsmdev` the page.
Found while trying to package mdevctl for [Debian/Ubuntu](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=945230)
> lsmdev - add the alternative name to the man page

- mdevctl
Try to defend against breaking out of the sysfs hierarchy via
the attribute names, e.g. '../../../../../../../../boo'.
> validate attribute names

- Makefile
Force installation of lsmdev and lsmdev.8 symlinks to make updates
to existing installs work.
> Force symlink cretion

- mdevctl.8
Signed-off-by: Erik Skultety <eskultet@redhat.com>
> man: Point --verbose to the 'list' command rather than 'types'

- mdevctl
As reported by coverity scan:
Defect type: SHELLCHECK_WARNING
1. /usr/sbin/mdevctl:544:13: warning: available appears unused. Verify use (or export if used externally). [SC2034]
This also fixes a conflict between `auto` and `available` short options,
with both using -a for it.
closes: #24
Signed-off-by: Eduardo Lima (Etrunko) <etrunko@redhat.com>
> Remove never used 'available' option

- mdevctl
If a vfio driver returns e.g. a write error while attribute data is
being populated into the system mdevctl exits without cleanup.
Here is an example with vfio-ap try to use the same queue resource
$ mdevctl list -dv
77773333-ea0e-4911-4911-aaaaaaaaaaaa matrix vfio_ap-passthrough manual
Attrs:
@{0}: {"assign_adapter":"7"}
@{1}: {"assign_domain":"3"}
77773333-ea0e-4911-4911-eeeeeeeeeeee matrix vfio_ap-passthrough manual
Attrs:
@{0}: {"assign_adapter":"7"}
@{1}: {"assign_domain":"3"}
$ mdevctl start -u 77773333-ea0e-4911-4911-aaaaaaaaaaaa
$ mdevctl list -d
77773333-ea0e-4911-4911-aaaaaaaaaaaa matrix vfio_ap-passthrough manual (active)
77773333-ea0e-4911-4911-eeeeeeeeeeee matrix vfio_ap-passthrough manual
$ mdevctl start -u 77773333-ea0e-4911-4911-eeeeeeeeeeee
/usr/sbin/mdevctl: line 264: …
> mdevctl: fix cleanup on error when writing to attribute

- Makefile
- mdevctl
- mdevctl.8
1) Fix an obvious bug where the path we call when a parent device appears only creates the mdev without applying attributes.
2) Add version command support.  The 'tag' make target will now modify the version variable in the mdevctl script, commit the change, and add the matching tag.  This is not too unlike kernel versions, where the Makefile is updated and a tag added to that commit with a matching version.
> Bug fix + version support

- mdevctl
Using a jsonfile like this
$ cat mdev_nodedev.json
{"mdev_type": "vfio-ccw_io", "start": "manual", "attrs":[]}
and calling mdevctl to define a definition as follows causes an error.
$ mdevctl define -p 0.0.0033 --jsonfile mdev_nodedev.json
/usr/sbin/mdevctl: line 183: /etc/mdevctl.d/0.0.0033/532d626a-40bb-4cc1-a8f5-3291b42039ed: No such file or directory
This is due a missing subdirectory creation in the base directory
/etc/mdevctl.d/ before writing the config in the define jsonfile case.
Signed-off-by: Boris Fiuczynski <fiuczy@linux.ibm.com>
> Fix define from jsonfile

- mdevctl.8
- src/main.rs
- src/tests.rs
- tests/start/defined-diff-type/defined.json
- tests/start/defined-multiple-underspecified/defined.json
- tests/start/defined-multiple-underspecified/defined/defined.json
- tests/start/defined-multiple/defined.json
- tests/start/defined-with-type/defined.json
- tests/start/no-type-parent-defined/defined.json
When running `start` and providing a uuid, parent, and type that match
an existing device definition, mdevctl was creating a new device and
starting that rather than starting the defined device. This normally
doesn't matter unless the defined device contains attributes, in which
case the newly started device won't have the expected attributes set.
Also add some tests to ensure correct behavior in these scenarios.
Fixes #38
Signed-off-by: Jonathon Jongsma <jjongsma@redhat.com>
> Fix unexpected behavior with 'start'

- Cargo.toml
- src/tests.rs
Tempdir has been merged with tempfile since tempfile 3.0.
Comparing the two usage codes of the TempDir struct [1] vs [2]
the change appear clear and only needed because mdevctl
uses a prefix (otherwise a change to the use reference would
have been enough).
[1]: https://github.com/rust-lang-deprecated/tempdir
[2]: https://docs.rs/tempfile/3.2.0/tempfile/struct.TempDir.html
Fixes: !44
Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>
> switch tempdir (deprecated) to tempfile

- 60-mdevctl.rules
- Makefile.in
- mdevctl.8
- src/callouts.rs
- src/environment.rs
- src/main.rs
- src/mdev.rs
- src/tests.rs
- tests/callouts/bad-json.sh
- tests/callouts/good-json.sh
- tests/callouts/params.sh
- tests/callouts/rc0.sh
- tests/callouts/rc1.sh
- tests/callouts/rc2.sh
- tests/callouts/template.sh
- tests/callouts/type-a.sh
- tests/callouts/type-b.sh
- tests/callouts/type-c.sh
- tests/list/active-callout-bad-json.json
- tests/list/active-callout-bad-json.text
- tests/list/active-callout.json
- tests/list/active-callout.text
Version "3" of the call-out implementation. Previous version is #35 
A few notable changes from the previous version (aside from all the rust):
- scripts are now stored in /etc/mdevctl.d/scripts.d/callouts and scripts.d/notifiers
- "script not supported for device type" error code changed from 95 (loosely related to OS error codes) to 2
More documentation can be read via the man page changes, but I'll post it all here so it's easier to read without all the formatting junk:
```
EXTERNAL SCRIPTS FOR DEVICE EVENTS
SYNOPSIS
<CONFIG> | SCRIPT <-t=type -e=event -a=action -s=status -u=UUID -p=parent>
DESCRIPTION
mdevctl  supports invoking external scripts to handle additional device-specific configuration
and event reporting. These scripts are invoked by mdevctl at various points during command …
```
> [v3] Callouts (rust impl)

- .github/workflows/release.yml
Add two new github workflow jobs that run when a new release is made.
In order to make packaging easier for downstream linux distributions,
we want to include a separate 'vendor' tarball alongside the mdevctl
source. In order to publish this tarball, add a new github workflow that
runs `cargo vendor` and uploads the vendor tarball to the appropriate
release page.
A second job uploads the new release to crates.io using a token that has
been added to the repository secrets.
Signed-off-by: Jonathon Jongsma <jjongsma@redhat.com>
> Add a github workflow for releases

- src/callouts.rs
- tests/callouts/rc0.sh
- tests/callouts/rc1.sh
- tests/callouts/rc2.sh
Downstream RHEL builds were failing sporadically due to some racy failures in the callout tests. Make the build more deterministic by fixing the race condition.
> Fix sporadic callout test failures

- src/environment.rs
- src/main.rs
When there are missing dirs or dirs with insufficient permissions, we weren't providing useful error messages. Make these a little easier to debug.
> Handle some config filesystem errors

- build.rs
Some distros (like Gentoo) does not have a "rst2man" but "rst2man.py". This PR allows to specify the path of the rst2man or different name of it.
> fix build.rs to allow specify exact path or name of the rst2man

- Cargo.toml
- build.rs
- src/cli.rs
- src/main.rs
Clap v3 has been out for some time now and it is intended as a successor
to the structop/clapv2. Port to this new API.
Signed-off-by: Jonathon Jongsma <jjongsma@redhat.com>
> Port CLI to clap v3

- Cargo.toml
- mdevctl.spec.in
- src/callouts.rs
- src/main.rs
- src/tests.rs
Alex found a couple issues while packaging the 1.2.0 release for fedora. This branch addresses both of them.
> Fix a couple build issues

- src/mdev.rs
Providing the maximum valid index plus one causes a panic on modify delattr command.
Here is an example:
$ mdevctl list -d -v
ed4654e5-12f2-4936-b079-4bba74d2c785 matrix vfio_ap-passthrough auto (active)
Attrs:
@{0}: {"testattr1":"testval1"}
@{1}: {"testattr2":"testval2"}
@{2}: {"testattr3":"testval3"}
$ mdevctl modify --delattr -i 3 -u ed4654e5-12f2-4936-b079-4bba74d2c785 thread 'main' panicked at 'removal index (is 3) should be < len (is 3)', src/mdev.rs:442:28 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Signed-off-by: Boris Fiuczynski <fiuczy@linux.ibm.com>
> Fix panic on modify delattr with invalid index

- src/cli.rs
- src/main.rs
- src/tests.rs
- tests/modify/jsonfile.expected
- tests/modify/modified.json
To allow updates of multiple attributes with a single mdevctl call adding the jsonfile optional parameter to command modify.
Signed-off-by: Boris Fiuczynski <fiuczy@linux.ibm.com>
> modify: add jsonfile optional parameter

- src/main.rs
- src/tests.rs
If a callout script returns with an error code the undefine method is not called and therefore the mdev is not undefined. The user should get notified this occured instead of silently suppressing the error when the mdev is not undefined.
> undefine: report error if device is not undefined

- Cargo.toml
- src/callouts.rs
- src/tests.rs
- tests/modify/callout-fail-force.expected
- tests/modify/callout-pass.expected
- Bump version to 1.3.0
- tests: make test failure reports more obvious
- tests: remove stray debug prints during fork
- tests: test 'stop' with callouts
- Bump 'nix' dependency
> Some test-related changes and other misc

- src/callouts.rs
- src/tests.rs
- tests/callouts/good-json-null-terminated.sh
A trailing null will make serde_json::from_str fail. Let's trim the string if a null is present to make it happy.
Fixes #84
Note, this will create a merge conflict in PR #83. If this change is acceptable, I can either rebase Boris' patches on top of this, or I can fit this patch in nicely after the conflicting commit.
> trim trailing null from callout script get-attributes output

- src/cli.rs
Prevent running mdevctl modify command without specifying either parameter addattr, delattr or jsonfile.
> modify: ensure required parameter is given

- src/cli.rs
Adjust help text for modify option addattr to match the other help texts.
> cli: adjust help text for modify option addattr

- src/cli.rs
Allow mdevctl modify command to use auto and manual parameters without using parameter addattr, delattr or jsonfile. Fixed missing requirement checks and improved error messages.
> modify: fix parameter relations and improve error messages

- src/cli.rs
Adding the long about help text to the lsmdev command help.
> cli: improve lsmdev help

- mdevctl.spec.in
Add systemd as build requirement as otherwise _udevrulesdir is not set correctly and the build fails with
File must begin with "/": %{_udevrulesdir}
> mdevctl.spec.in: Add systemd as build requirement

- src/main.rs
Active devices are created from loading the sysfs information. Autostart is the only attribute that must be retrieved from the persisted configuration if it exists. Instead of loading the persisted configuration into the retrieved active mdev data which overwrite valid active mdev settings be more surgical and use a new mdev for loading the configuration and the only copy the autostart attribute to the active mdev.
> main: assemble active devices without overwriting

- Cargo.toml
This is only used as a test dependency. There is no need to pull this in for package builds. Moreover, it should not be listed as a dependency.
> Cargo.toml: move tempfile to dev-dependencies

- Cargo.toml
- mdevctl.rst
- src/callouts.rs
- src/cli.rs
- src/environment.rs
- src/main.rs
- src/tests.rs
- tests/callouts/live-rc0.sh
- tests/callouts/live-rc1.sh
- tests/callouts/modify-active.sh
- tests/callouts/ver-rc0-get-attr-bad-json.sh
- tests/callouts/ver-rc0.sh
- tests/callouts/ver-rc1.sh
- tests/modify/defined-only.active.expected
- tests/modify/defined-only.defined.expected
- tests/modify/live-defined-supported.active.expected
- tests/modify/live-defined-supported.defined.expected
- tests/modify/live-event-supported.expected
- tests/modify/modify-jsonfile-with-version-callout-all-pass.expected
- tests/modify/modify-jsonfile-with-version-callout-multiple-with-version-pass.expected
- tests/modify/modify-jsonfile-with-version-callout-multiple-with-version-pass2.expected
The first patch fixes a clippy warning encountered on github.
The next six patches are callout version support related.
The fifth patch adds code preventing repeating callouts when version lookup failed before addressing a comment I made in v3.
The last six patches add live modify support exploiting the callout version support.
Changes in v6:
Inlined supports_action and supports_event
Renamed CalloutExport/Import into CalloutVersionProvides/Supports
Fixuped callouts: lookup_callout_script more rustified
Changed lookup_callout_script to use simple string compare
Changes in v5:
Rewrote the manpage to better work out the expectation wrt the versioning JSON exchange.
Split CalloutExchange into CalloutExport and CalloutImport and removed skip_serializing_if.
Renamed CalloutScript into …
> Callout version live v6

- src/environment.rs
Fixing this error reported in the CI:
error: assigning the result of `Clone::clone()` may be inefficient
--> src/environment.rs:168:21
|
168 |                     per_dev.parent = dev.parent.clone();
|                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `clone_from()`: `per_dev.parent.clone_from(&dev.parent)`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assigning_clones
= note: `-D clippy::assigning-clones` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::assigning_clones)]`
error: could not compile `mdevctl` (bin "mdevctl") due to 1 previous error
Error: Process completed with exit code 101.
> Fix clippy problem on master
